apiVersion: v1
kind: Service
metadata:
  name: blog-mysql
  labels:
    run: blog
spec:
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 30306
      name: sql
  selector:
    run: blog-sql
  type: NodePort
